defaults:
  - ppo_trainer
  - user
  - _self_

# GRPO + TTRL voting (no SDPO distillation)
max_model_len: 18432

actor_rollout_ref:
  actor:
    ppo_mini_batch_size: 32
  rollout:
    n: 32
    calculate_log_probs: True

algorithm:
  adv_estimator: grpo
  norm_adv_by_std_in_grpo: False
  rollout_correction:
    rollout_is: token
    rollout_is_threshold: 2.0

data:
  train_batch_size: 32

trainer:
  val_before_train: True

ttrl:
  enable: True
  voting_strategy: majority  # majority | zero_filtered_majority | complexity_aligned | golden_answer
  solver_name: gurobi  # "gurobi" or "copt" (for StepORLM)
  n_votes_per_prompt: 32 #no use currentlly
  n_samples_per_prompt: 32 #no use currentlly
  use_or_template: False
  lp_selection_target: voted_answer  # voted_answer | golden_answer
